class SourceType:
    MERAKI = "Meraki"
    PORTAGENT = "PortAgent"
    CLIENT = "Client"


class CommunicationFlag:
    PDA_REQUEST = "PDA REQUEST"
    PDA_SUBMIT = "PDA SUBMIT"
    PDA_RETURN = "PDA RETURN"
    PDA_UPDATE = "PDA UPDATE"
    PDA_RE_REQUEST = "PDA RE-REQUEST"
    PDA_RETURN_RE_REQUEST = "PDA RETURN RE-REQUEST"
    PDA_RE_SUBUMIT = "PDA RE-SUBMIT"
    CLIENT_APPROVAL_REQUEST = "CLIENT APPROVAL REQUEST"
    PDA_CLIENT_SUBMIT = "PDA CLIENT SUBMIT"
    FDA_CREATION = "FDA CREATION"
    FDA_UPDATE = "FDA UPDATE"
    FDA_SUBMIT = "FDA SUBMIT"
    FDA_CLIENT_SUBMIT = "FDA CLIENT SUBMIT"

class CountryName:
        CHINA='CHINA'
        INDIA='INDIA'
        TURKEY='TURKEY'
        EGYPT='EGYPT'
        RUSSIA='RUSSIA'
